spring:
  profiles:
    active:
      - local
    group:
      local:
        - db-local
        - rabbitmq-local
        - prompt-local
      prod:
        - db-prod
        - rabbitmq-prod
        - prompt-prod
    include:
      - oauth
      - db
      - rabbitmq
      - prompt

server:
  port: 8000

logging:
  level:
    org:
      springframework: info
      hibernate:
        type:
          descriptor:
            sql: trace #query의 ?에 어떤 값이 들어가는 지 표기
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"

jwt:
  secret: test123test1234test123test1234test123test1234test123test1234
  access_time: 300000000 #5분
  refresh_time: 1800000 #7일

rabbitmq:
  exchange:
    name: image-creation-exchange
    type: direct

  queue:
    request:
      name: image-creation-request-queue
      routing-key: image.creation.request
    response:
      name: image-creation-response-queue
      routing-key: image.creation.response

aws:
  S3:
    access_key: AKIAWAXHFZI3ZEUQVOG3
    bucket_name: dreamgream-image-bucket
    region: ap-northeast-2
    secret_key: Hj8gu3eE+KSnNV2baFrL3Ceeq2mgPLxwtXRSoWsY


